### ISSUE TITLE
May remove the mobile first code.

### ISSUE THREAD

**Issue by juanbzz** [thinkxl/tequila.scss#2]
Maybe remove this: https://github.com/thinkxl/hyx.scss/blob/master/hyx.scss#L10-L11so anyone can use mobile first if they wanted like this:

``` scss
.full-width {
  width: 100%;
  float: none;
}

.col-1-2 {
  @extend .full-width;

  @media handheld, only screen and (min-width: 768px) {
    @include cols(1/2);
  }
}
```
